
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://123.56.68.131:3306/b_cms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Lx753369
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      test-while-idle: false
      pool-prepared-statements: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: redis
    password: cms2022


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # Âß¼­É¾³ýÅäÖÃ
    db-config:
      # É¾³ýÇ°
      logic-not-delete-value: 1
      # É¾³ýºó
      logic-delete-value: 0


logging:
  level:
   root: info
  path: /app/logs
  file:
    max-history: 10
    max-size: 1024MB

